id: I7753427C
legacy_id: P003258
ocr_import_info:
  bdrc_scan_id: W1KG10193
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T07:16:42'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T02:16:33.853592+00:00'
last_modified: 2022-08-31 10:26:20.321112
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG10193
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG10193
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། འཇིགས་མེད་གླིང་པ།
  author: ཀུན་མཁྱེན་འཇིགས་མེད་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.7298915562418012
  ocr_word_median_confidence_index: 0.7799999713897705
quality: null
bases:
  I1KG10196:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10196
      total_pages: 1007
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG10196.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7381205056666696
    legacy_id: v002
  I1KG10197:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10197
      total_pages: 883
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG10197.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.698275488426939
    legacy_id: v003
  I1KG10198:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10198
      total_pages: 923
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG10198.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.7048805181211881
    legacy_id: v004
  I1KG10200:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10200
      total_pages: 521
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG10200.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7386283745803619
    legacy_id: v006
  I1KG10203:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10203
      total_pages: 867
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I1KG10203.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7866559412435952
    legacy_id: v009
  I1KG10199:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10199
      total_pages: 898
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG10199.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6805221945125731
    legacy_id: v005
  I1KG10195:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10195
      total_pages: 935
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10195.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.7997445141036005
    legacy_id: v001
  I1KG10202:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10202
      total_pages: 1424
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1KG10202.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.735653724486101
    legacy_id: v008
  I1KG10201:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10201
      total_pages: 1296
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1KG10201.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.711543144648643
    legacy_id: v007
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
