id: I7753427C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T07:24:14+00:00'
last_modified: '2022-06-07T18:41:55.736104+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10193
  title: གསུང་འབུམ། འཇིགས་མེད་གླིང་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    D417:
      image_group_id: I1KG10195
      title: ''
      total_pages: 935
      order: 1
      base_file: D417.txt
    4B6C:
      image_group_id: I1KG10196
      title: ''
      total_pages: 1007
      order: 2
      base_file: 4B6C.txt
    308E:
      image_group_id: I1KG10197
      title: ''
      total_pages: 883
      order: 3
      base_file: 308E.txt
    D395:
      image_group_id: I1KG10198
      title: ''
      total_pages: 923
      order: 4
      base_file: D395.txt
    3F93:
      image_group_id: I1KG10199
      title: ''
      total_pages: 898
      order: 5
      base_file: 3F93.txt
    B0B7:
      image_group_id: I1KG10200
      title: ''
      total_pages: 521
      order: 6
      base_file: B0B7.txt
    B68C:
      image_group_id: I1KG10201
      title: ''
      total_pages: 1296
      order: 7
      base_file: B68C.txt
    E77B:
      image_group_id: I1KG10202
      title: ''
      total_pages: 1424
      order: 8
      base_file: E77B.txt
    '0436':
      image_group_id: I1KG10203
      title: ''
      total_pages: 867
      order: 9
      base_file: 0436.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
